### ISSUE TITLE
Here is the code used to parse the descriptions for the first cut

### ISSUE THREAD

**Issue by kevinoconnell** [openoakland/soft-story-buildings#1]
*STATA 12.1
index           int    %10.0g                 index
Street          int    %10.0g                 Street#
StreetName      str15  %15s                   StreetName
StreetType      str4   %9s                    StreetType
City            str7   %9s                    City
State           str2   %9s                    State
lat             byte   %10.0g                 lat
H               byte   %10.0g                 long
Parcel          str13  %13s                   Parcel #
Record          str8   %9s                    Record #
RecordType      str10  %10s                   Record Type
Status          str8   %9s                    Status
FiledDate       int    %td..                  Filed Date
StatusDate      int    %td..                  Status Date
Description     str142 %142s                  Description
RelatedRecords  byte   %10.0g                 Related Records
Balance         double %10.0g                 Balance
Level           byte   %10.0g                 Level
Exempted        str1   %9s                    Exempted
Unit            str21  %21s                   Unit

*Description holds most of the detail.  By parsing parts of it, we can create other variables.  We want to get number of units, Level of substructure problem, and if they are exept.
*Task 1:  Split apart at number of units.
split Description, p(",")
split Description2 , p("unit")

Task 2:  Split apart at Level, code for level #
gen level = strpos( Description1,"Level") & strpos(Description1, "LEVEL")

*Split apart at except
gen exept=1 if level==.

**Comment by kevinoconnell** [comment]
Hey dave--
I need to tweak this a bit.  I added the data dictionary for kicks, but it
wont run.  this is more for posterity, so we can tweak it.

**Comment by daguar** [comment]
Cool, thanks for the note. Still helpful as documentation.

On Wed, Feb 12, 2014 at 9:06 AM, kevinoconnell notifications@github.comwrote:

> Hey dave--
> I need to tweak this a bit. I added the data dictionary for kicks, but it
> wont run. this is more for posterity, so we can tweak it.
> 
> On Wed, Feb 12, 2014 at 8:50 AM, Dave Guarino <notifications@github.com
> 
> > wrote:
> > 
> > Closed #1 <https://github.com/openoakland/soft-story-buildings/issues/1
> > via
> > #3 <https://github.com/openoakland/soft-story-buildings/pull/3>.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/openoakland/soft-story-buildings/issues/1>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openoakland/soft-story-buildings/issues/1#issuecomment-34890757
> .

## 

Dave Guarino
2013 Fellow, Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ |
GitHubhttps://github.com/daguar/
