### ISSUE TITLE
Geocode the data

### ISSUE THREAD

**Issue by daguar** [openoakland/soft-story-buildings#2]
Since I do think some part of this project will make use of the ["stuff on a map"](https://github.com/codeforamerica/civic-tech-patterns#stuff-on-a-map) design pattern, we need to [geocode](http://en.wikipedia.org/wiki/Geocoding) the data -- essentially, get a latitude and longitude for each building.

The two quickest approaches I see:
1. Use the raw address data and put it into a bulk geocoder (examples, [BatchGeo](http://batchgeo.com/), [Data Science Toolkit](http://www.datasciencetoolkit.org/))
2. Use the parcel ID in the data with Alameda County's public parcel layer (computing the "centroid" [lat/long at the center of the shape] of each parcel)

Please comment if you're interested in taking this on.

**Comment by spjika** [comment]
I got this. We have a high accuracy parcel and street based geocoder for alameda county.

**Comment by daguar** [comment]
BOOM. Assigned. If you can, add a comment to this issue with a link to a file rather than committing into the repo for now, since I'm still unsure how I want to handle data management (within/outside git.)

**Comment by max-mapper** [comment]
@daguar do you have a link to the "Alameda County's public parcel layer" referenced above? I wanna play around with building a custom geocoder index. @spjika if you have any additional links to parcel + address data for AC it would be appreciated too!

I found https://data.acgov.org/Government/Alameda-County-Parcel-Boundaries/2m43-xsic but am not sure its the right data

**Comment by daguar** [comment]
@spjika's your point on this; he knows the canonical sources way better than me.

**Comment by spjika** [comment]
we published the latest versions on data.openoakland.org yes. County parcel
layer and assessors secured roll. LMK if you need dif versions.

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by daguar** [comment]
And here's the link to that @maxogden: http://data.openoakland.org/dataset/assessor-s-parcel-boundary

**Comment by max-mapper** [comment]
this one looks pretty good too https://data.acgov.org/Government/Alameda-County-Secondary-Addresses/8e4s-7f4v

**Comment by max-mapper** [comment]
oh nice! http://data.openoakland.org/dataset/assessor-secured-roll-2013-parcels "data available to the public should you directly purchase the DVD in person." hahahha

**Comment by daguar** [comment]
Bug @spjika to tell you about "the $15,000 file" some time.

**Comment by max-mapper** [comment]
@spjika in the Assessor Secured Roll 2013 Parcels data, what is the background on the "MA street address" versus the "Situs street address"? are "MA" and "situs" two different data sources?

**Comment by spjika** [comment]
Situs is the actual property. MA is mailing address for the owner. Not
always the same even for owner occupied properties.

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by max-mapper** [comment]
@spjika this dataset doesn't have latitude/longitude http://data.openoakland.org/dataset/assessor-secured-roll-2013-parcels, do you know if there is a version that does?

this dataset ("Secondary Addresses") seems to have lots of addresses + latitude/longitude, do you know where it came from? https://data.acgov.org/Government/Alameda-County-Secondary-Addresses/8e4s-7f4v

**Comment by spjika** [comment]
never used that secondary address file sorry. I can prob add the lat/longs
to the parcel file sure.

Dave- do you not want me to pull request the geocoded data then? Load it
elsewhere? I have a csv and a geojson file prepared with lat/longs of all
the soft story locations, got 100% done and seems to be super accurate.

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by daguar** [comment]
@spjika Could you put the CSV on Google Drive, make it public, and post the link here?

**Comment by spjika** [comment]
geocoded data in wgs84 web mercator auc sphere:
https://drive.google.com/file/d/0BwNZYWcpRBQ7aS1ZZklER0FhV0U/edit?usp=sharing

lat/longs included in the file. 100% complete.

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by max-mapper** [comment]
@spjika I wanna use the secured roll data for building my own geocoder for fun, so if there isn't lat/long available in the raw data then don't worry about geocoding it (that would kind of defeat the purpose I think)

**Comment by spjika** [comment]
it isn't no, but it won't hurt for me to
1) extract Oakland form the updated county parcel file w assessor data
2) convert to lat/long
3) create coordinates
4) export to csv

do it?

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by max-mapper** [comment]
@spjika don't worry about it for now, thanks though. do you have a link to the oakland county parcel data you're using? this one doesn't have any data files attached: http://data.openoakland.org/dataset/assessor-s-parcel-boundary

**Comment by spjika** [comment]
http://data.openoakland.org/en/dataset/assessor-secured-roll-2013-parcels/resource/248941cb-ae8f-4676-b00a-5586ce22ed7f

Parcels for Oakland in web friendly csv with the centriods as lat/long.
There will be a few park/regional space type shapes that don't geocode well
as the centroids aren't perhaps contained in their shape, same with a few
hairy regular parcels with battleaxe shapes.

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by daguar** [comment]
Why don't we build a micro service?

Send a parcel ID, get a lat long 

Was super common use for me, and seems like a good shares OpenOak infrastructure.

**Comment by daguar** [comment]
Actually, it could even just be a URL mask on the CKAN URL, eg:

`GET http://parcels.openoakland.org/parcel?id=1234567`
