### ISSUE TITLE
Add URL to project description

### ISSUE THREAD

**Issue by fureigh** [openoakland/soft-story-buildings#22]
This is such a great project! Thanks, @daguar et al.

I see that the site is up at http://softstory.openoakland.org. It'd be rad to add that URL to the project description so people finding this repo in other ways — like by browsing Open Oakland's repos, as I was just doing :) — can view the live site without having to stand it up locally.

**Comment by daguar** [comment]
Howdy — the actual repo for that site is the one that the site links to, namely https://github.com/openoakland/oakland-soft-story-map rather than this one.

**Comment by daguar** [comment]
Added a note to this effect on the GitHub front page of this repo

**Comment by fureigh** [comment]
Oh, whoops. Thanks for clarifying!

**Comment by daguar** [comment]
No worries! A bit confusing I know.
