### ISSUE TITLE
verify that source data is complete

### ISSUE THREAD

**Issue by max-mapper** [openoakland/soft-story-buildings#6]
oddly enough the csv from scribd is exactly 1000 rows of data. maybe the export isn't complete? does someone who can wanna comment on that recordtrac issue and ask?

**Comment by spjika** [comment]
arghh., I cleaned/geocoded a crap file? Nooo

I'll start again with the fill file from Dave's email.

fk

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by daguar** [comment]
Nice catch, @maxogden! I got caught up in the ecstasy of getting data in the first place.

There's no way in RecordTrac for a requester to follow up on a response in the app (CC @criscristina ) so I'm going to email the contacts in the Department.

**Comment by daguar** [comment]
Oh, and @spjika, the Excel file sent by Jim over email is _also_ only 1,000 rows, so hold off on re-doing the work.

**Comment by spjika** [comment]
already checked that too, on hold senor!

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by daguar** [comment]
Email sent; Jim (the public records liaison) is out of the office, but I
CC'd him and contacted the Building Dept folks who I think put together the
response directly.

On Wed, Feb 12, 2014 at 11:15 AM, Spike notifications@github.com wrote:

> already checked that too, on hold senor!
> 
> Spike
> openoakland.org
> www.stealingbeautyphotography.com
> 
> On Wed, Feb 12, 2014 at 11:15 AM, Dave Guarino <notifications@github.com
> 
> > wrote:
> > 
> > Oh, and @spjika https://github.com/spjika, the Excel file sent by Jim
> > over email is _also_ only 1,000 rows, so hold off on re-doing the work.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/openoakland/soft-story-buildings/issues/6#issuecomment-34904852
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openoakland/soft-story-buildings/issues/6#issuecomment-34904932
> .

## 

Dave Guarino
2013 Fellow, Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ |
GitHubhttps://github.com/daguar/

**Comment by daguar** [comment]
Just got this update from the city:

"Thank you for your interest in our soft-story housing improvement plan.

As of today , we received only 1,000 screening responses from 1,379 sent notices."

I followed up to ask for the full list of 1379 buildings, but it looks like the 1000 is in fact the complete set for screenings submitted.

**Comment by max-mapper** [comment]
wow! nice

**Comment by spjika** [comment]
then carry on, data I loaded is it then till we get the missing ones from
ABAG

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by daguar** [comment]
FYI, Rachel has confirmed for ABAG that the City permits them to release the raw data to us. So the ball's in their court.
